### ISSUE TITLE
fix download link in solarus site

### ISSUE THREAD

**Issue by itslooklike** [MaxMraz/yarntown#14]
Hello 👋

I try to download game, but got 404 error =(

Link in https://www.solarus-games.org/en/games/yarntown not correct

![image](https://user-images.githubusercontent.com/17547664/89097814-15847900-d3eb-11ea-97f5-e5d5f461bfa0.png)

https://github.com/MaxMraz/yarntown/releases/download/v1.0.5/data.solarus

actual is: https://github.com/MaxMraz/yarntown/releases/download/v1.0.5/yarntown.solarus

**Comment by oclero** [comment]
Fixed! See https://gitlab.com/solarus-games/solarus-website-pages/-/merge_requests/175
This issue can be closed.
