### ISSUE TITLE
Media files license questions

### ISSUE THREAD

**Issue by Wuzzy2** [MaxMraz/yarntown#15]
> Graphic, music, and .dat assets are all rights reserved.

Two questions:

1) Why?
2) Who is the official copyright holder?

**Comment by MaxMraz** [comment]
1. They're renditions of From Software's IP. 
2. The same person who holds the copyright on any fan art. Or in the case of the tileset and music, me.

**Comment by Wuzzy2** [comment]
Thanks for the answer.

**Comment by MaxMraz** [comment]
: )
You bet
