### ISSUE TITLE
Enemies

### ISSUE THREAD

**Issue by Chude1** [MaxMraz/yarntown#4]
I am no savy when it comes to this and I can't get that the enemies appear ¿how do I do this?

**Comment by MaxMraz** [comment]
I'm sorry, I'm not sure what you're asking. Can you please give more details?

**Comment by Chude1** [comment]
No no I'm sorry, english isn't my first language. The eemie won't load, I launch the game from the Solarus Launcher with the quest.dat file and the enemies don't appear

**Comment by MaxMraz** [comment]
That's fine! : )
What OS are you using?
Are there any errors in the Solarus launcher?

**Comment by Chude1** [comment]
Sorry ¿what' OS?  - I figured it out-           I'm using windows
the launcher said there were errors but with breakable.lua

**Comment by MaxMraz** [comment]
OS = Operating System. For example: Windows, Mac, Linux.

What did the errors say?

**Comment by Chude1** [comment]
Error: In collision callback: entities/breakable.lua:51: attempt to call method 'start_agro' (a nil value)
stack traceback:
[C]: in function 'start_agro'
entities/breakable.lua:51: in function 'destroy'
entities/breakable.lua:33: in function <entities/breakable.lua:23>

I'm using Windows, Im pretty sure I checked when the solarus site asked me wich one I picked that one

**Comment by MaxMraz** [comment]
Yes, I do not think the Mac or Linux launcher will work on Windows ; )

Yes, the function 'start_agro' is related to enemies.

I will try to get a windows machine to investigate.

**Comment by Chude1** [comment]
Thanks! The game looks amazing tho! Great job

**Comment by MaxMraz** [comment]
Hmm, just tried on a windows machine and I'm not having an issue

Maybe try downloading from here?
https://www.solarus-games.org/en/games/yarntown

**Comment by MaxMraz** [comment]
Idk what the issue was but it seems to have just been with this dude's machine
